baseURL = 'https://blog.nradk.com/'
languageCode = 'en-us'
title = "Neeraj Adhikari's blog"
theme = 'etch'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10 

  [[menu.main]]
    identifier = "talks"
    name = "talks"
    title = "talks"
    url = "/talks"
    weight = 15 

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about"
    weight = 20 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$$', '$$$']]
          inline = [['$$', '$$']]

[params]
  math = false

